### ISSUE TITLE
package:crclib/catalog.dart not found

### ISSUE THREAD

**Issue by sami-samcla** [google/crclib.dart#12]
Hi.
This problem occurs on iOS and Android platforms.

The Flutter environment:
```
[✓] Flutter (Channel dev, 1.27.0-4.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-4.0.pre at /Users/sissa/flutter
    • Framework revision f8cd24de95 (9 weeks ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sissa/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/sissa/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • PRA LX1 (mobile)         • 9DC7N17707001642                         • android-arm64  • Android 7.0 (API 24)
    • SAMCLA’s iPhone (mobile) • f063d3c4cfd212cac4386163446403a522fa40cb • ios            • iOS 14.4.2
    • Chrome (web)             • chrome                                   • web-javascript • Google Chrome 89.0.4389.128

• No issues found!
```

My pubspec.yaml dependencies:

```
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  crclib: ^2.0.0
  flutter:
    sdk: flutter

  flutter_blue:
    git:
      url: git://github.com/pauldemarco/flutter_blue.git

  webdav_client: ^1.0.0

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.5
  test:

publish_to: none
```
When I try to build the app, throw this error:

```
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Error: Could not resolve the package 'crclib' in 'package:crclib/catalog.dart'.
    ../ota_package/lib/ota/utils/download_manager/download_manager_impl.dart:1:8: Error: Not found: 'package:crclib/catalog.dart'
    import 'package:crclib/catalog.dart';
           ^
    ../ota_package/lib/ota/utils/download_manager/download_manager_impl.dart:69:24: Error: The method 'Crc32' isn't defined for the class 'DownloadManagerImpl'.
     - 'DownloadManagerImpl' is from 'package:ota_package/ota/utils/download_manager/download_manager_impl.dart' ('../ota_package/lib/ota/utils/download_manager/download_manager_impl.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'Crc32'.
        String crcResult = Crc32().convert(otaDownloadedFile.getRange(0, otaDownloadedFile.length - 4).toList()).toRadixString(16);
                           ^^^^^
    Unhandled exception:
    FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Acrclib%2Fcatalog.dart; message=StandardFileSystem only supports file:* and data:* URIs)
    #0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
    #1      asFileUri (package:vm/kernel_front_end.dart:599:37)
    #2      writeDepfile (package:vm/kernel_front_end.dart:738:21)
    <asynchronous suspension>
    #3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:558:9)
    <asynchronous suspension>
    #4      starter (package:flutter_frontend_server/server.dart:180:12)
    <asynchronous suspension>
    #5      main (file:///opt/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
    <asynchronous suspension>


    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

Error launching application on SAMCLA’s iPhone.
```

**Comment by postmasters** [comment]
I'm sorry that you are hitting an issue with crclib. I can't seem to reproduce it, however. Did you forget to `flutter pub get` or `pub get`?

```shell
$ cat pubspec.yaml 
name: test
environment:
        sdk: ">=2.7.0 <3.0.0"
dependencies:
        crclib: ^2.0.0
publish_to: none
$ /usr/lib/google-dartlang/bin/pub get
Resolving dependencies... (1.1s)
+ crclib 2.0.0
+ matcher 0.12.10
+ meta 1.3.0
+ path 1.8.0
+ quiver 2.1.5 (3.0.1 available)
+ stack_trace 1.10.0
+ tuple 1.0.3 (2.0.0 available)
Downloading crclib 2.0.0...
Downloading tuple 1.0.3...
Downloading meta 1.3.0...
Downloading quiver 2.1.5...
Downloading matcher 0.12.10...
Downloading stack_trace 1.10.0...
Downloading path 1.8.0...
Changed 7 dependencies!
$ cat main.dart
import 'package:crclib/catalog.dart';

int main() {
  print(Crc32().convert([0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39]).toRadixString(16));
  return 0;
}
$ /usr/lib/google-dartlang/bin/dart main.dart 
cbf43926
```

**Comment by sami-samcla** [comment]
Hi.
I have updated Dart version (from 2.7.0 to 2.12.4) and now works fine.
The crclib package it's installed on a pure Dart project, not a Flutter project. The local Dart version was different than uses Flutter sdk.

Thanks for your response.

**Comment by postmasters** [comment]
Glad you've found a solution.
